name:  Deploy TreinaZap to S3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
         node-version: 12.21.0
         name: INSTAL AWS CLIENTE
         run: pip install awscli
      - name: INSTALL E BUILD 
        run: npm install && npm run build
        env:
           CI: "false"
      - name: DEPLOY S3
        run: cd build && AWS_ACCESS_KEY_ID=AKIAYR4V437NN26JXL23 AWS_SECRET_ACCESS_KEY=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 aws s3 sync . s3://luizproject --acl public-read --delete
      
         
        
